spring.application.name=table-tennis-club-manager

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tabletennis}
spring.datasource.username=${DB_USERNAME:clubadmin}
spring.datasource.password=${DB_PASSWORD:clubpassword}
